sudo: required
dist: trusty
group: deprecated-2017Q4

language: generic

services:
- docker

script:

- echo 'IMG_NAME="Raspbian"' >> config

# only build up to stage 2. We don't have enough space for NOOBS on travis.
- touch ./stage5/SKIP

- ./build-docker.sh
- ls -lahR deploy
- "[ -s deploy/*.zip ]"
